### ISSUE TITLE
Wait screen just for the table ?

### ISSUE THREAD

**Issue by senthilthyagarajan** [JohnCoene/waiter#1]
Is it possible to show the wait screen only on the table that's being refreshed rather than the whole page? I am using a Datatable and wanted to know if that is possible.

**Comment by JohnCoene** [comment]
waiter is really designed for full-screen if you want a spinner on a single output there is, amongst others [shinycssloaders](https://github.com/andrewsali/shinycssloaders)

**Comment by senthilthyagarajan** [comment]
Thank you. I really like this as a full-screen spinner.

**Comment by JohnCoene** [comment]
I just added loading screens for individual elements, i.e.: `datatable` :) [demo here](https://shiny.john-coene.com/waiter/)

**Comment by senthilthyagarajan** [comment]
Awesome. It looks great. Thank you.
