### ISSUE TITLE
List underlying JavaSript or CSS libraries

### ISSUE THREAD

**Issue by nteetor** [JohnCoene/waiter#10]
Either in the DESCRIPTION or in the README it would be useful to see a list of names or links to any of the underlying JavaScript or CSS libraries used by {waiter}.

**Comment by JohnCoene** [comment]
Yes indeed, bad practice of me, it's now in the README, thanks.

**Comment by nteetor** [comment]
Awesome, thank you! This package saved me quite a bit of work and time today.
