### ISSUE TITLE
waiter_show_on_load no longer takes logo argument

### ISSUE THREAD

**Issue by bitowaqr** [JohnCoene/waiter#101]
I was able to use waiter_show_on_load with a logo argument, but this now seems to be deprecated. After updating the package, it gives me an error. I fixed it by just passing it as an img(...) in tagList, but might create compatibility issues for other people?

**Comment by JohnCoene** [comment]
Thank you for flagging this. I had correctly deprecated the argument in some functions but erroneously removed it from others.
