### ISSUE TITLE
Waitress for Shiny   rmarkdown::render progress

### ISSUE THREAD

**Issue by BerndMaier** [JohnCoene/waiter#104]
Hi,
first thanks for this awesome package :+1: 

This is more of a question than an issue with the package itself.

I wanted to ask if I can use waitress to replace the (not so nice looking)
shiny withProgress for rendering markdown reports.

As waitress is much more beautiful.

Can waitress use the `shiny::setProgress` information from Markdown or sth like that to show the rendering progress?

Thank you very much and keep up the nice work,
Bernd

**Comment by JohnCoene** [comment]
Good idea, let me think how this could work.

**Comment by JohnCoene** [comment]
I just pushed this feature. I cannot override the `progress` object that Shiny uses internally so I have to create separate functions.

```r
library(shiny)
library(waiter)

ui <- fluidPage(
  useWaitress(),
  br(),
  actionButton(
    "load",
    "Load stuff"
  )
)

server <- function(input, output) {
  observeEvent(input$load, {
    withProgressWaitress({
      for (i in 1:15) {
        incProgressWaitress(1)
        Sys.sleep(0.25)
      }
    }, selector = "#load", max = 15, theme = "overlay-percent")
  })
}

shinyApp(ui, server)
```

Hope this helps.

**Comment by BerndMaier** [comment]
Thanks for the fast improvement - yeah, works fine, used the attendant as it looks really nice and allows extra messages :+1:
