### ISSUE TITLE
Add a text box below the spinner

### ISSUE THREAD

**Issue by SimonCoulombe** [JohnCoene/waiter#115]
Hi!
First, thanks for creating this.  It is super useful for my shiny apps, which needs a good 30 seconds to prepare data at startup.

I was wondering if it was possible to add a text box to the spinner during those 30 seconds.

It would basically an "about" box, telling people what the app is for and how to use it.  

Once the spinner disappears, they could be on the "About" tab, so they could keep reading.

thanks

**Comment by JohnCoene** [comment]
Yes, this is shown [here](https://waiter.john-coene.com/#/waiter/intro#customise) the `html` argument accepts any {shiny} `tag`

**Comment by SimonCoulombe** [comment]
ooh, I had missed it. Thanks!

https://waiter.john-coene.com/#/waiter/intro#customise

**Comment by jmestret** [comment]
Hi!
In reference to the above post, I have successfully implemented dynamic messages with the spinner. However, my current approach feels somewhat unfancy, and I'm wondering if there is a cleaner alternative. The problem arises when trying to switch from the spinner to a Hostess loader while simultaneously updating messages. Is it possible to update messages while updating the hostess progress?

Below, I have attached the method I used with the spinner.

Thank you very much!

```
library(shiny)
library(waiter)

ui <- fluidPage(
    useWaiter(),
    actionButton("show", "Show loading with updates")
)

server <- function(input, output, session){
    # create the waiter
    waiting_screen <- tagList(
        spin_flower(),
        h4("Cool stuff loading...")
    )
    w <- Waiter$new(html = waiting_screen)
    
    msgs <- c("Loading data", "Running model", "Drawing plots")
    
    observeEvent(input$show, {
        w$show()
        
        Sys.sleep(2)
        
        for(i in 1:3){
            w$update(html = tagList(
                spin_flower(),
                h4(msgs[i])
            ))
            Sys.sleep(2)
        }
        
        w$hide()
    })
}

shinyApp(ui, server)
```
