### ISSUE TITLE
Usage of rcpp package

### ISSUE THREAD

**Issue by nteetor** [JohnCoene/waiter#12]
I happened to look into the `src/` folder and discovered the only exported function contains a series of if else statements. 

Was there a reason Rcpp is necessary for `themes_to_js()`? If Rcpp is unecessary, removing the package could drop a lot of overhead. 

I forked the package and moved the C++ function into a standalone R function. I didn't notice any problems, but perhaps there's a chance I didn't catch an edge case.

**Comment by JohnCoene** [comment]
The reason was stupidity from my side, a PR is most welcome.

**Comment by JohnCoene** [comment]
Thanks Nate, I built the documentation and merge.
