### ISSUE TITLE
waitress on top right does not dissapear after waitress$close()

### ISSUE THREAD

**Issue by pachadotdev** [JohnCoene/waiter#124]
I followed https://waiter.john-coene.com/#/waitress#notifications to have `waitress_1`, `waitress_2`, etc. When the progress bar finishes, the elements for the corresponding tab are ok, but the progress bar does not disappear on close.

Here's what I'm doing https://github.com/pachadotdev/tradestatistics-visualization-with-shiny/commit/2d2f1cce1d6a8e3389dd7c72119cfbbd5bd5e764

Please tell me how I can help to fix this.

![Screenshot from 2022-06-20 18-18-56](https://user-images.githubusercontent.com/10091065/174684253-82cb3cad-cd07-43d1-a274-7c107f23c7cf.png)

**Comment by JohnCoene** [comment]
Do you have a reproducible example? I can't run your [repo](https://github.com/pachadotdev/tradestatistics-visualization-with-shiny) and the example in the documentation works just fine.
