### ISSUE TITLE
Use spinners with waitress

### ISSUE THREAD

**Issue by samssann** [JohnCoene/waiter#14]
There should be the ability to use spinners with waitress (just like waiter).

```
shinyApp(
  ui = fluidPage(plotOutput("test")),
  server = function(input, output, session) {
    output$test <- renderPlot({
      w <- call_waitress("#test", spin_fading_circles())
      w$start()
      p <- hist(rnorm(100))
      w$hide()
      p
    })
  }
)
```

**Comment by JohnCoene** [comment]
Hi Sam,

Two things, 1) the "waitress" does no use spinners, it's a loading bar. 2) place `use_waitress` in the UI.

```r
shinyApp(
  ui = fluidPage(
    use_waitress(),
    plotOutput("test")),
  server = function(input, output, session) {
    output$test <- renderPlot({
      w <- call_waitress("#test")
      w$start()
      Sys.sleep(1)
      p <- hist(rnorm(100))
      w$hide()
      p
    })
  }
)
```

**Comment by samssann** [comment]
Yes, I meant it would be a great addition if waitress could use spinners in the future. (label: enhancement). 

Otherwise there is no way to use a spinner for a single plot?

**Comment by JohnCoene** [comment]
No, {waiter} was originally designed to have splash loading screens, if you want a spinner on a single plot there is:

- @andrewsali [shinycssloaders](https://github.com/andrewsali/shinycssloaders)
- @emitanaka [shinycustomloader](https://github.com/emitanaka/shinycustomloader)
