### ISSUE TITLE
Left navbar is not properly alligned

### ISSUE THREAD

**Issue by P-Potdar** [JohnCoene/waiter#141]
<img width="207" alt="Screenshot 2023-10-07 at 1 13 14 PM" src="https://github.com/JohnCoene/waiter/assets/109173669/957c2c76-8403-474f-bd2e-2691994b24d1">

**Comment by P-Potdar** [comment]
Need to add dropdown and I would definitely like to do it

**Comment by JohnCoene** [comment]
Sure, a PR is most welcome!

**Comment by Ajay-308** [comment]
hey can you assign this issue to me!

**Comment by P-Potdar** [comment]
@JohnCoene assign me the issue I will definitely fix it
