### ISSUE TITLE
Python shiny plans?

### ISSUE THREAD

**Issue by iainmwallace** [JohnCoene/waiter#144]
Awesome package! Just wondering if you might have any plans of releasing a similar one for shiny in python

**Comment by JohnCoene** [comment]
I've been thinking about it.
I know py-shiny uses the same JavaScript dependencies as shiny so much of it should be easy to transfer.

However, I don't have much knowledge of Python not time. If anyone wants to take this on feel free to reuse the JavaScript used here.

**Comment by crazycapivara** [comment]
Hi @iainmwallace, @JohnCoene
we just released a first version of `py-waiter` at https://github.com/eodaGmbH/py-waiter.
At the moment only `waiter.js` is supported. Feel free to test it and create issues and feature requests.

@JohnCoene Thanx for the js code, we just included it in the python package.

**Comment by JohnCoene** [comment]
Oh man this is cool!
