### ISSUE TITLE
Using Waiter on Tabpanel

### ISSUE THREAD

**Issue by AnuradhaSurendra** [JohnCoene/waiter#147]
Hi, 
I am new to using Waiter and I am wonder how to use it to block all elements on a tabpanel. I have tried the following:

```r
    waiter_show( id="tabA"
      html = spin_fading_circles() # use a spinner
    )
```

But that does not work.

**Comment by JohnCoene** [comment]
We can't do that because tab ids are dynamically generated but we can wrap the tab in a `div`, assign it an `id` and use that instead.

```r
navbarPage(
  "page",
  tabPanel(
    "first",
    div(
      id = "first", 
      ...,
      style = "min-height:100vh" # optional but may make it look nicer
    )
  )
)
```

Then use 

```r
waiter_show( 
  id="first"
)
```

**Comment by AnuradhaSurendra** [comment]
John, thank you. This worked perfectly!

**Comment by JohnCoene** [comment]
Good to hear!
