### ISSUE TITLE
README should include basic usage

### ISSUE THREAD

**Issue by hadley** [JohnCoene/waiter#17]
The full website is great, but it would be very handy if the README could quickly remind you of the major use cases.

**Comment by JohnCoene** [comment]
Hi Hadley, 

Thank you for the feedback, you couldn't be more right: I've added more details and examples in README.

**Comment by hadley** [comment]
Looks great, thanks!  It would also be handy to have a table that briefly describes the difference between butler, waiter, and waitress.

**Comment by JohnCoene** [comment]
Indeed. I will add that once all other issues have been ironed out.

**Comment by hadley** [comment]
You might also mention the aide-memoire of prog**ress** = wait**ress**

**Comment by JohnCoene** [comment]
Note to self:
prog<strong>ress</strong> - wait<strong>ress</strong>
spinn<strong>er</strong> - wait<strong>er</strong>

**Comment by JohnCoene** [comment]
I've added basic examples and a brief table with features to the README, inspired by that of [rtweet](https://github.com/ropensci/rtweet). Any suggestion is welcome.

**Comment by JohnCoene** [comment]
Thanks again Hadley, I think this is now fixed, going ahead and closing.
