### ISSUE TITLE
Suboptimal print method

### ISSUE THREAD

**Issue by hadley** [JohnCoene/waiter#22]
``` r
library(waiter)
waitress <- Waitress$new()
waitress
#> [1] "A waitress on the whole screen."
```

This makes it look like the object is a string. Instead, it would be better to use `cat()` and produce something like:

```R
waitress
#> <waitress> A waitress on the whole screen
```

**Comment by JohnCoene** [comment]
All R6 classes now use `cat` those that did not have a print method (e.g.: `butler`) now have one.
