### ISSUE TITLE
show_waiter customization

### ISSUE THREAD

**Issue by OGuggenbuehl** [JohnCoene/waiter#3]
Is it possible to customize the splash page beyond just the background color? Ideally I'd like to add a short text with customizable color and also change the color of the spinners. 
I realize that some of these may be possible by using `tagList()`, but that in turn makes it impossible to add a logo or change the color argument.

**Comment by JohnCoene** [comment]
It's doable but certainly not intuitive as you have to go look into the source code to understand what CSS to apply.

```r

library(waiter)
library(shiny)

ui <- fluidPage(
  use_waiter(), # dependencies
  tags$head(
    tags$style(".sk-fading-circle .sk-circle:before{background-color:red;}")
  ),
  actionButton("show", "Show loading for 5 seconds")
)

server <- function(input, output, session){
  
  observeEvent(input$show, {
    show_waiter(
      div(
        style = "color:red;",
        spin_fading_circles(),
        "Loading ..."
      )
    )
    Sys.sleep(3)
    hide_waiter()
  })
}

if(interactive()) shinyApp(ui, server)
```

Namely by looking at the [spinkit.css](https://github.com/JohnCoene/waiter/blob/master/inst/assets/waiter/spinkit.css) to see which class to change to modify the spinners and the spinner's respective classes in the [R file](https://github.com/JohnCoene/waiter/blob/master/R/spinners.R).

I'll flag that as improvement for the next version, in the meantime please let me know which spinners you'd like to modify and I'll let you know how to.

Thanks for reporting this!

**Comment by OGuggenbuehl** [comment]
Thank you for your prompt response! Ideal for me would be if the function had arguments such as `show_waiter(html = NULL, logo = NULL, text = NULL, text-color = NULL, background-color = NULL)`. 

Currently I'm looking to add a logo, set the background to white and turn `spin_wandering_cubes()` as well as a string ("loading...") red. 

Your time and effort is much appreciated!

**Comment by OGuggenbuehl** [comment]
Ist it possible to also set the background color of the loading screen from your example above? I tried adding it via `div(
        style = "color:red;
                      background-color;white",
        spin_fading_circles(),
        "Loading ..."
      )`

but that only changed a small frame around the spinner instead of the entire background.

**Comment by JohnCoene** [comment]
The function `show_waiter` has been deprecated in favour of `waiter_show` in the latest (dev/not-on-CRAN version) but includes nearly all these arguments.

```r
library(shiny)
library(waiter)

ui <- fluidPage(
  use_waiter(), # include dependencies
  actionButton("show", "Show loading for 3 seconds")
)

server <- function(input, output, session){

  screen <- div(
    style="color:red;",
    spin_3(),
    h3("Loading Stuff")
  )

  # create a waiter
  w <- Waiter$new(
    html = screen,
    color = "black"
  )

  # on button click
  observeEvent(input$show, {
    w$show()
    Sys.sleep(3)
    w$hide()
  })
}

shinyApp(ui, server)
```

Feel free to reopen if this is not what you were after.
