### ISSUE TITLE
Add a NEWS file (or other changelog)

### ISSUE THREAD

**Issue by davidski** [JohnCoene/waiter#34]
Thank you very much for the nifty package!

Please consider adding a NEWS.md or some other form of changelog. There are some light notes on the releases tab of GitHub, but there are CRAN version releases (v0.0.6 and v0.0.1, for example) which don't have matching releases here on GitHub so it's currently difficult to track what has been changing between releases.

Thanks again!

**Comment by JohnCoene** [comment]
Yes indeed, bad practice of me, will try to remedy to this best I can.

**Comment by JohnCoene** [comment]
Add a [changelog](https://waiter.john-coene.com/#/changelog) on the website and the standard [NEWS.md](https://github.com/JohnCoene/waiter/blob/master/NEWS.md), will try to backtrack changes as best I can.

**Comment by JohnCoene** [comment]
I'm going to go ahead and close this as I believe this has been addressed, NEWS.md and changelog are available on github and the website. Thanks for raising this issue.
