### ISSUE TITLE
Is it possible to avoid Sys.sleep with a dynamic waiter?

### ISSUE THREAD

**Issue by tyluRp** [JohnCoene/waiter#38]
The following example from the documentation doesn't work if you comment out the `Sys.sleep` call. I couldn't find an explanation in the docs but I may have missed it. 

Is there a way to avoid sleeping? I have an app that (unfortunately) loads way to much data at once, so every second we can avoid is nice to have.

```
library(shiny)
library(waiter)

ui <- fluidPage(
  use_waiter(),
  actionButton("show", "Show loading with updates")
)

server <- function(input, output, session){
  # create the waiter
  w <- Waiter$new(html = span("Initialising"))
  
  msgs <- c("Loading data", "Running model", "Drawing plots")
  
  observeEvent(input$show, {
    w$show()
    
    # Sys.sleep(2) <---------------- here
    
    for(i in 1:3){
      w$update(html = msgs[i])
      Sys.sleep(2)
    }
    
    w$hide()
  })
}

shinyApp(ui, server)
```

I am using waiter_0.1.0.9000 and shiny_1.4.0, so unsure if this is due to the development version.

**Comment by JohnCoene** [comment]
Hi Tyler,

Thanks for reporting that. Indeed it does not work currently; the full-screen loading page relies on an external library that appears which though has the option to show updates instantaneously appears not to work.

Please bare with me while I find a solution.

**Comment by JohnCoene** [comment]
This is an issue with the underlying JavaScript library that powers the full page loading screen, and does not currently affect the partial loading screen.

```r
library(shiny)
library(waiter)

ui <- fluidPage(
  use_waiter(),
  actionButton("show", "Show loading with updates"),
  plotOutput("plot")
)

server <- function(input, output, session){
  # create the waiter
  w <- Waiter$new("plot", html = span("Initialising"))

  msgs <- c("Loading data", "Running model", "Drawing plots")

  output$plot <- renderPlot({
    input$show
    w$show()

    Sys.sleep(2)

    for(i in 1:3){
      w$update(html = msgs[i])
      Sys.sleep(.1)
    }

    hist(runif(100))
  })
}

shinyApp(ui, server)
```

Sorry, this might take some time to debug.

**Comment by JohnCoene** [comment]
Note: remove underlying dependency and redo full-screen waiter with vanilla or jQuery

**Comment by JohnCoene** [comment]
I know it's taken a very long time but I have finally removed the underlying dependency and this issue is resolved: feel free to reopen if you encounter any problem. Thanks for your patience.
