### ISSUE TITLE
Feature suggestion: Reverse Loading effect and Curtain Opening

### ISSUE THREAD

**Issue by LucasMelo3** [JohnCoene/waiter#4]
Dear @JohnCoene,

It would be very cool to have the **Waitress on the whole page** in the way it's loading effect goes 'reverse' where it starts full and as it's loads then starts to show the content.

Likewise, it would also be cool to **Open a Curtain effect** , where the screen starts full and the reverse effects happen divided from the middle to the sides of the page.

How difficult is it to implement?
I would also be happy to help if you show me the way.

Btw, thanks for sharing this awesome package!

**Comment by JohnCoene** [comment]
Hi Lucas,

I'm very sorry for the late response, I've been swamped lately. Your ideas are great and I would love to see them implemented in the package. However I only used external libraries to do all these loading animations, their respective source code is [here](https://github.com/JohnCoene/waiter/tree/master/inst/assets).

If you find one that you would like to see added please feel free to share it with me, I'd love to add more also share a name, we have a butler, waiter, and waitress already :)

If you know how to code it in JS from scratch feel feel to do so, I'm happy to build the R/Shiny wrapper.

**Comment by LucasMelo3** [comment]
I have a clue how it can be done, using as base the CSS animation from waitress/progress.min.css then implement the effect using this working example on [CodePen](https://codepen.io/geoffgraham/pen/aZbJBw). 😃
