### ISSUE TITLE
README file suggestion

### ISSUE THREAD

**Issue by jhk0530** [JohnCoene/waiter#44]
Hi, 

I think you did really awesome work. I like this. 

but I think readme can be modified little bit.

1. in Feature table
If you don't mind it will be better to center align elements, 
and check mark can be better if you use not backgrounded check mark.

Here's my suggestion

|Feature|Waiter|Waitress|Hostess|
|:---:|:---:|:---:|:---:|
|Progress Bar|:heavy_check_mark:|:heavy_check_mark:|:heavy_check_mark:|
|Full Screen|:heavy_check_mark:|:heavy_check_mark:|:x:|
|Works with waiter|:heavy_check_mark:|:x:|:heavy_check_mark:|
|Spinner|:heavy_check_mark:|:x:|:x:|
|Updatable|:heavy_check_mark:|:x:|:x:|
|Notifications|:x:|:heavy_check_mark:|:x:|

2. in Example code (in `waitress`)

As package suggests with warning message,

`increase` method should be changed with `inc` method.
`w$increase(10)` -> `w$inc(10)`
`hide` method should be changed with `close` method.
`w$hide()` -> `w$close()`

Regards.

**Comment by JohnCoene** [comment]
Thank you for that, you're right. I just pushed changes though I thought that if we are to use `: heavy_check_mark:` we ought to use `:heavy_multiplication_x:` for the crosses. What do you reckon?

|      Feature      |           Waiter           |          Waitress          |          Hostess           |
| :---------------: | :------------------------: | :------------------------: | :------------------------: |
|   Progress Bar    |    :heavy\_check\_mark:    |    :heavy\_check\_mark:    |    :heavy\_check\_mark:    |
|    Full Screen    |    :heavy\_check\_mark:    |    :heavy\_check\_mark:    | :heavy\_multiplication\_x: |
| Works with waiter |    :heavy\_check\_mark:    | :heavy\_multiplication\_x: |    :heavy\_check\_mark:    |
|      Spinner      |    :heavy\_check\_mark:    | :heavy\_multiplication\_x: | :heavy\_multiplication\_x: |
|     Updatable     |    :heavy\_check\_mark:    | :heavy\_multiplication\_x: | :heavy\_multiplication\_x: |
|   Notifications   | :heavy\_multiplication\_x: |    :heavy\_check\_mark:    | :heavy\_multiplication\_x: |

**Comment by jhk0530** [comment]
I like both. :blush:

**Comment by JohnCoene** [comment]
Thanks, I'll keep it this way then. Feel free to open any other issues if you run into problems or have other suggestions 👍
