### ISSUE TITLE
Reduce CSS size / dynamic loading

### ISSUE THREAD

**Issue by fmannhardt** [JohnCoene/waiter#47]
Thanks for this nice package. Looks and works great, Would it be possible to use dynamic loading of the CSS files (or embed them in the page) to only include those that are actually needed?

The core CSS file has about 140 KB which is a lot only for displaying loading bars.

**Comment by JohnCoene** [comment]
Yes! It had not occurred to me but makes of course complete sense. Let me work on that.

**Comment by JohnCoene** [comment]
So. I can't actually dynamically load the CSS based on the spinner user. Perhaps something could be hammered together with JavaScript but it would not be clean. So instead I allow loading just the necessary files. I have the idea detailed [here in the docs](https://waiter.john-coene.com/#/waiter?id=css-load).

Essentially you can reduce the load size of the CSS files in `use_waiter` which now takes a `spinners` argument to which one can specify any of 7 spinner CSS kits, by default all kits are loaded so nothing breaks. You can know which kits should be specified by simply typing the spinner in the console, e.g.: `spin_rotating_plane()`

**Comment by fmannhardt** [comment]
Thanks for the very quick response. Works great. Only thing is that it now prints the message about which `kit` to use all the time. So, maybe this should be moved somewhere else or only when called from the console?

**Comment by JohnCoene** [comment]
Yes, indeed, that was annoying! I just fixed that.

**Comment by JohnCoene** [comment]
I'm going to close this for now as I think this has been addressed, though admittedly further segmentation of the CSS can be done. Thank you for raising this issue.
