### ISSUE TITLE
waiter_show_on_load showing before plots show up

### ISSUE THREAD

**Issue by vacon04** [JohnCoene/waiter#51]
As the title states. Not much of a reprex unfortunately, but I can explain the issue. After using  waiter_show_on_load, the waiting screen goes away before some charts finish loading. The charts are some maps and graphs done by another one of your packages, echarts4r (thanks for it by the way, great job!)

More than trying to debug it, I was wondering if there is any way to add some extra time to the waiter_hide function?

Currently I'm usin the use_waiter(include_js = FALSE) as stated in the website, and the waiter_hide function waiter_hide( ).

Thanks!

**Comment by JohnCoene** [comment]
You can have the waiter dynamically hide when a certain element is rendered with the function `waiter_hide_on_render` and precising the id of the element to watch for render (plot, table, anything rendered from shiny server). There's a bit of documentation [here](https://waiter.john-coene.com/#/waiter?id=on-render).

A small example

```r
library(shiny)
library(waiter)

ui <- fluidPage(
  use_waiter(),
  waiter_show_on_load(),
  plotOutput("plot"),
  waiter_hide_on_render("plot")
)

server <- function(input, output){

  output$plot <- renderPlot({
    Sys.sleep(2)
    plot(cars)
  })

}

shinyApp(ui, server)
```

Let me know if this answers your question.

**Comment by vacon04** [comment]
Awesome, for some reason I thought I could only use the waiter_hide_on_render on the server side. What a great wait to lose an hour of my time.

Thank you very much man, keep up the good work, and stay safe.

**Comment by PaulC91** [comment]
Hi @JohnCoene 

Is it possible to use this `waiter_show_on_load(), waiter_hide_on_render("id")` but for shiny modules? 

In my case have several navbar tabs, the ui and server elements of each are module functions and I only run the server module function when the tab is selected for the first time.

I want a full screen waiter to show when a new tab is selected for the first time and only hide when a particular element within that tab is rendered.

My current method (below) suffers from the same issue the OP had in that the waiter hides long before graphics are rendered on the page (there is one particular tab with a leaflet map and lots of highcharts so rendering takes some time)

```r
# in server function
# this runs when the tab is selected for the first time
w$show()
callModule(mod_server, "id")
w$hide()
```

Cheers!
