### ISSUE TITLE
waiter_show / hide does not work wrapped aorund a process 

### ISSUE THREAD

**Issue by Nightstar0** [JohnCoene/waiter#52]
Hi there, Firstly I wanted to that the waiter package is brilliant ! and like how these loading screens can help joe public feel at ease when using a shiny application :). However I do unfortunately have a issue trying to use waiter_show / waiter_hide when being wrapped around a process 

e.g.  i have the following code in the server area  that currently works (kinda)

                                    addressMatched <- reactive({ 
                                                                req(input$aM)
                                                                waiter_show(html  = div(style = 'color:#FFFFFF;',spin_folding_cube(),'Address job Processing. This will take a while...')
                                                                                        ,color = '#20508c')
                                                                Sys.sleep(3)
                                                                on.exit(waiter_hide())
                                                                df1 <- read.csv('data/dummy_address_match.csv'))
                                                               })

So at present it will load up the waiter screen , and after will then process the data and render it onto the screen. however i need to have the waiter screen showing whilst the read.csv code is running (can take a while dependant on file size), is there something i am missing.

do let me know if i can provide any more asistance or code to help answer this issue, thank you ! :)

**Comment by Nightstar0** [comment]
so in other words, i thought this should work based on the above :


                                addressMatched <- reactive({ 
                                                            req(input$aM)
                                                            waiter_show(html  = div(style  = 'color:#FFFFFF;',spin_folding_cube(),'Address job Processing. This will take a while...')
                                                                                    ,color = '#20508c')
                                                            df1 <- read.csv('data/dummy_address_match.csv'))                                                           
                                                            Sys.sleep(3)
                                                            on.exit(waiter_hide())
                                                                             })

However, whilst it completes, the rendered window is just blank ...

**Comment by JohnCoene** [comment]
Hi,

Thanks opening this issue.

When you wrap `waiter_hide` in `on.exit` the loading is screen is hidden when the reactive is done executing, in other words after the csv is file has been read.

The issue lies elsewhere/afterwards. I assume that you do further processing on said CSV file and probably output some kind of visualisation/table; the loading screen is hidden before these are visible.

I suggest you either look at [on render](https://waiter.john-coene.com/#/waiter?id=on-render) to have the waiting screen hide when a visual is rendered, or that you place `waiter_hide` elsewhere. 

Let me know if this helps, otherwise please share a working example of your app so I can show you how.

**Comment by Nightstar0** [comment]
Hi There! thank you for getting back to me so quickly ! :) I will try as you suggested now , and failing that will supply with the rest of the code. either way I will let you know how i get on.

Thank you for your advice so far :)

**Comment by Nightstar0** [comment]
Hi again, 
 
So tried both methods and no joy im afraid ....

looked at the on render section of the waiter page and did as suggested , by placing the relevant id there, so the csv file did process and rendered the information on screen, but no loading screen had appeared.

on the other hand, I had placed the waiter_hide() within the output section refelected reactive code, and the opposite effects happens! so the csv doesnt load, but the loading screen will appear and hang there for some time :S.
[app - to check - Copy.txt](https://github.com/JohnCoene/waiter/files/4503792/app.-.to.check.-.Copy.txt)

[dummy_address_match.txt](https://github.com/JohnCoene/waiter/files/4503794/dummy_address_match.txt)



I have attached code with the current code in place at present (stipped down version for ease of reading)

**Comment by Nightstar0** [comment]
So in the above scenario , it appears to be working as you would expect, but if that csv file was instead a complicated function that produced a dataframe as a result  (and takes ages!) then after a 3 second loading screen that disappears, you would just see a blank window for however long the function takes ( in my case 30 minutes) until you get the results on the screen . 

So anything you can assist with to ensure i can make this as user friendly as possible , i would be most greatful !

**Comment by JohnCoene** [comment]
Here are reproducible examples.

## Using on Render

This is recommended as it hides the loading screen when the plot is actually apparent on screen.

```r
library(shiny)
library(waiter)

read_a_csv <- function(){
  runif(10^8) # "large" dataset
}

ui <- fluidPage(
  use_waiter(),
  actionButton("upload", "Upload CSV"),
  plotOutput("plot"),
  waiter_hide_on_render("plot")
)

server <- function(input, output){

  react <- eventReactive(input$upload, {
    waiter_show()
    read_a_csv()
  })

  output$plot <- renderPlot({
    hist(react())
  })
}

shinyApp(ui, server)
```

## Using on.exit

This will present you with a white screen for a while as the plotting functions take a while to draw 10^8 points.

```r
library(shiny)
library(waiter)

read_a_csv <- function(){
  runif(10^8) # "large" dataset
}

ui <- fluidPage(
  use_waiter(),
  actionButton("upload", "Upload CSV"),
  plotOutput("plot")
)

server <- function(input, output){

  react <- eventReactive(input$upload, {
    waiter_show()
    on.exit(waiter_hide())
    read_a_csv()
  })

  output$plot <- renderPlot({
    hist(react())
  })
}

shinyApp(ui, server)
```

**Comment by JohnCoene** [comment]
Did this help you solve the issue?

**Comment by Nightstar0** [comment]
Good Morning , 

Thank you for providing this information. I can confirm that the hide_on_render sugesstion worked like a charm  for one of them :) it did not work as well for the other process(much less worried about anyway) . In other words, you have solved my issue thank you !!!. 

P.s. again loving this package, so any way I can contribute, I would be happy to help :)

All the best
