### ISSUE TITLE
Control fade/ease effect for fullscreen Waiter?

### ISSUE THREAD

**Issue by mmuurr** [JohnCoene/waiter#53]
Hi, love the package.
Wondering if there's a way to turn off (or generally control) the easing/fading in/out of the full-screen Waiter presentation?
In particular, I'd like to shorten (or remove) the easing altogether.

**Comment by JohnCoene** [comment]
Sorry for coming back to you on this so very late! I will see what can be done about this.

**Comment by s-Nick-s** [comment]
+1 on this
waiter_on_busy is very nice, but fading out entire UI whenever something is loading scares my users :smile:

**Comment by JohnCoene** [comment]
Latest dev version has a new `fadeout` argument.

```r
library(shiny)
library(waiter)

ui <- fluidPage(
  useWaiter(), # include dependencies
  actionButton("show", "Show loading for 3 seconds")
)

server <- function(input, output, session){
  # create a waiter
  w <- Waiter$new(
    fadeout = TRUE # may also be boolean
  )

  # on button click
  observeEvent(input$show, {
    w$show()
    Sys.sleep(3)
    w$hide()
  })
}

shinyApp(ui, server)
```
