### ISSUE TITLE
using waiter with flexdashboard

### ISSUE THREAD

**Issue by nitingupta2** [JohnCoene/waiter#55]
I tried using `waiter` in a shiny app built using `flexdashboard`. Though the full page loading screen works, `waiter` doesn't seem to work with only parts in the application. For instance, I'm trying to show waiting screens before a table or a plot is rendered when the data is updated. 

Does `waiter` have compatibility issues with `flexdashboard`?

**Comment by JohnCoene** [comment]
Not that I know of. I know some dashboards use waiter with flexdashboard, e.g.: [text 2036](https://github.com/texas-2036/covid_tracker).

Could tell me more about the issue and share a reproducible example so I can look into it?

**Comment by nitingupta2** [comment]
Thanks for the prompt response. But the link you sent is of an app built using `shinydashboard`. However, a shiny app built in Rmd using [flexdashboard](https://rmarkdown.rstudio.com/flexdashboard/index.html) is where `waiter` doesn't appear to work when applied to parts in the application.

**Comment by JohnCoene** [comment]
Apologies, I got them mixed up, could you share a reproducible example demonstrating the issue so I can look for a potential fix please?

**Comment by nitingupta2** [comment]
Thanks! Here's a test `flexdashboard` shiny app I created to use `waiter` before rendering a table.
Please paste the contents below in a .Rmd file to reproduce the problem I mentioned.

---
title: "Test Flexboard Shiny App"
runtime: shiny
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(shiny)
library(tidyverse)
library(waiter)
```


Sidebar {.sidebar}
-----------------------------------------------------------------------

```{r}
selectInput("data_set", "Pick a dataset", choices = c("mtcars","airquality"), selected = "mtcars")

use_waiter()
```

```{r}

waiting_screen <- tagList(
  spin_flower(),
  h4("Initializing...")
) 


# Input dataset
mydataset <- reactive({

  name <- input$data_set

  waiter_show(html = waiting_screen, color = "black")
  Sys.sleep(3)
  
  df <- switch(name,
               "mtcars" = mtcars,
               "airquality" = airquality)
  
  return(df)
})
```


Column {data-width=1000}
-----------------------------------------------------------------------

### renderTable (reactive)

```{r}

renderTable(mydataset(), rownames = TRUE)
```

**Comment by JohnCoene** [comment]
I've been looking into this but I'm not sure it's ever going to work in an Rmarkdown with shiny runtime given the whole application is actually contained in an embed within a static document. Sorry about that.
