### ISSUE TITLE
hide_waiter() executed when page not completely loaded

### ISSUE THREAD

**Issue by mchibok** [JohnCoene/waiter#6]
I'm setting up a shiny application that is using a quite large Leaflet map (26 Mb) and takes approximately 5-10 seconds to load and it seems to be messing with the `show_waiter_on_load()` function.

The app also a very simple plot, a small dataframe and another Leaflet map that are available for the user to choose within the `sidebarPanel()` with `radioButtons()`. When I load the app without the large map, everything works immediately: I can see and switch between the plot, table and small map. However, when I include the bigger map, the `sidebarPanel()` shows first but the `mainPanel()` hangs until (I think) the map is fully loaded. During that time, I can interact with the different `radioButtons()` but nothing happens.

In both cases (with or without the large map), the loading screen is shown for about 2 seconds and goes away. In other words, it seems that the loading screen function doesn't seem to "check" whether the map is loaded or not.

I'm not very used to web programming but it seems like there are 2 loading steps (or more). I checked in the function `show_waiter_on_load()` and i'm wondering how I could change the `'DOMContentLoaded'` event for something else. I tried what I found online, like `load` or `onload`, but it's not working.

I was wondering if you would know of something else to check to correct this problem, or even if there was a possibility to show the loading screen for a minimum amount of time, regardless of load status. Is there anyway to check if everything on the page is loaded?

Hope my exaplanations were clear, thanks for your help.

Here is the set-up without the maps.
```
require(shiny)
require(leaflet)
require(waiter)

df <- data.frame(x = 1:3,
                y = 4:6,
                z = 7:9)

ui <- fluidPage(
  use_waiter(),
  show_waiter_on_load(tagList(spin_fading_circles(),
                              tags$br(), tags$h4(style="color:white;", "Loading ..."))),
  sidebarLayout(
    sidebarPanel(
      radioButtons(
        inputId = "show",
        label = "Visualise",
        choices = c("Plot", "Traffic", "Map")
      ),
      conditionalPanel(condition = "input.show == 'Map'",
                       radioButtons(
                         inputId = "map",
                         label = "Map choice",
                         choices = c("Time range", "Load profile")
                       ))),
    mainPanel(
      conditionalPanel(condition = "input.show == 'Plot'",
                       plotOutput("plot.p")),
      conditionalPanel(condition = "input.show == 'Traffic'",
                       tableOutput("table.p")),
      conditionalPanel(condition =
                         "input.show == 'Map' && input.map == 'Time range'",
                       leafletOutput("small.map", height = 600)),
      conditionalPanel(condition =
                         "input.show == 'Map' && input.map == 'Load profile'",
                       leafletOutput("large.map", height = 600))
  )))

server <- function(input, output) {
  output$plot.p <- renderPlot({
    plot(df$x, df$y)
  })
  
  output$table.p <- renderTable({
    df
  })
  
  # maps not rendered
  # output$map.range <- renderLeaflet({
  #   small.map
  # })
  # 
  # output$map.charge <- renderLeaflet({
  #   large.map
  # })

  hide_waiter()
  
}

shinyApp(ui, server)
```

**Comment by JohnCoene** [comment]
Hi thanks for the question.

I think I know why, because the map is a in a conditional panel it is not drawn when the app is loaded and therefore the time to compute not taken into account: the waiting screen is removed before the app is done computing what it needs to do.

In the app below the waiting screen is shown correctly.

```r
library(shiny)
library(leaflet)
library(waiter)

ui <- fluidPage(
  use_waiter(),
  show_waiter_on_load(spin_fading_circles()),
  leafletOutput("hugeMap")
)

server <- function(input, output) {

  reactive_quakes <- reactive({
    Sys.sleep() # this takes a long time
    quakes
  })
   
  output$hugeMap <- renderLeaflet({
    leaflet(data = reactive_quakes()) %>% addTiles() %>%
      addMarkers(~long, ~lat)
  })
  
  hide_waiter()
}

shinyApp(ui, server)
```

Now similar app but with a conditional panel, we observe the same issue you are reporting.

```r
library(shiny)
library(leaflet)
library(waiter)

ui <- fluidPage(
  use_waiter(),
  show_waiter_on_load(spin_fading_circles()),
  radioButtons(
    inputId = "show",
    label = "Show map",
    choices = c("No map", "map")
  ),
  conditionalPanel(
    condition = "input.show == 'map'", 
    leafletOutput("hugeMap")
  )
)

server <- function(input, output) {

  reactive_quakes <- reactive({
    Sys.sleep(5) # this takes a long time
    quakes
  })
   
  output$hugeMap <- renderLeaflet({
    leaflet(data = reactive_quakes()) %>% addTiles() %>%
      addMarkers(~long, ~lat)
  })
  
  hide_waiter()
}

shinyApp(ui, server)
```

Now take a look at the app below. Since I moved the heavy computation in a reactive that hides the waiter when done computing. Note that `hide_waiter` returns a value so make sure you use `return` (see #2 ).

```r
library(shiny)
library(leaflet)
library(waiter)

ui <- fluidPage(
  use_waiter(),
  show_waiter_on_load(spin_fading_circles()),
  radioButtons(
    inputId = "show",
    label = "Show map",
    choices = c("No map", "map")
  ),
  conditionalPanel(
    condition = "input.show == 'map'", 
    leafletOutput("hugeMap")
  )
)

server <- function(input, output) {

  reactive_quakes <- reactive({
    Sys.sleep(5) # this takes a long time
    q <- quakes
    hide_waiter()
    return(q)
  })
   
  output$hugeMap <- renderLeaflet({
    leaflet(data = reactive_quakes()) %>% addTiles() %>%
      addMarkers(~long, ~lat)
  })
  
}

shinyApp(ui, server)
```

Let me know if this does not make sense, I'm not sure I make a great job explaining it.

**Comment by mchibok** [comment]
Hi,
Thanks for your help.

I must say that I get the same behavior in the 1st example you posted (without the conditional panel). Loading screen for ~2 seconds, than blank screen for whatever duration is in `Sys.sleep()` before the map loads. I would think that the the loading screen would show until the map is loaded.

I did try with your method and I get the same result, with or without the `reactive({})` part. Approximately 2 seconds of loading screen, seeing the side panel, then about 5 seconds before the plot shows up (meaning, I assume, everything is loaded).

```
react.map <- reactive({
    lm <- large.map
    hide_waiter()
    return(lm)
  })
   
  output$hugeMap <- renderLeaflet({
    react.map()
  })
```

Note, however, that I am not creating the map `large.map` in the `renderLeaflet({})` bit. I don't know if that could change something, but I doubt it. The thing is I created the large map beforehand, saved it in a '.RData' file and then simply load it in the script.
```
load("largemap.RData") # loading large.map, a 'Large leaflet (8 elements, 25.9 Mb)'

# [some code creating ui]

server <- function(input, output) {
   output$hugeMap <- renderLeaflet({
      large.map
   })
}
```
The reason I did that is because creating the map takes ~25 seconds and it's way too long to be created on the server side. It's 1900 separate polylines generated from lat long coordinates added with a loop, where the size of every line represent passenger load in buses for a certain period, looking something like this :

![2019-08-20 10_43_31-Simulations REM - Charge](https://user-images.githubusercontent.com/25492081/63359749-459e4d80-c33b-11e9-9a8c-2a584e5d4c94.png)


So i'll leave the app as is for now and try to create the map differently so that it is smaller and takes less time to load.

Thanks again for your help and for the package!

**Comment by JohnCoene** [comment]
OK I understand the issue better now. The problem is that `hide_waiter` is triggered server side not client side.

The object (map) takes 2 seconds to `load` and prepare server side but takes 5 seconds to render in the browser, hence the issue the waiting is removed after the object is loaded, not after it is actually drawn on screen.

I have just added a function to hide the waiter when a certain visualisation is drawn.

Reinstall the package from Github.

```r
# install.packages("remotes")
remotes::install_github("JohnCoene/waiter")
```

Then try the app below, notice there is not hide function in the server, it's all in the UI.

```r
library(shiny)
library(leaflet)
library(waiter)

ui <- fluidPage(
  use_waiter(),
  show_waiter_on_load(spin_fading_circles()),
  radioButtons(
    inputId = "show",
    label = "Show map",
    choices = c("No map", "map")
  ),
  conditionalPanel(
    condition = "input.show == 'map'", 
    leafletOutput("hugeMap")
  ),
  hide_waiter_on_drawn("hugeMap") # pass the id of ouput to watch
)

server <- function(input, output) {
   
  output$hugeMap <- renderLeaflet({
    leaflet(data = quakes) %>% addTiles() %>%
      addMarkers(~long, ~lat)
  })
  
}

shinyApp(ui, server)
```

This, if not perfect, should already be better. Let me know.

**Comment by mchibok** [comment]
This is great!
Thank you so much, works perfectly!
