### ISSUE TITLE
Question : using waiter with downloadHandler

### ISSUE THREAD

**Issue by chalioui** [JohnCoene/waiter#60]
Hello John! can you provide an example of using waitress to display a loading bar when downloading a file from a shiny app 
Thank you :)

**Comment by JohnCoene** [comment]
Hi,

Sorry for getting back to you so late. Could you tell me more about what you have in mind exactly?

**Comment by garciamikep** [comment]
I believe I have this same question and can provide more detail.  I have an app that allows users to download a powerpoint file (via `{officer}`) with graphs and tables created in the app. It takes long enough to render the plots and create the powerpoint that I'd like to notify the user that the download is in progress and they don't think the app is broken.

Here's a simple modification of [this example](https://shiny.rstudio.com/reference/shiny/0.14/downloadHandler.html), with the download speed artificially inflated by 5 seconds. I'd like to use `{waiter}` to display a notification and/or progress bar while waiting for the download to complete.

```
if (interactive()) {
  library(shiny)
  ui <- fluidPage(
    downloadLink("downloadData", "Download")
  )
  
  server <- function(input, output) {
    # Our dataset
    data <- mtcars
    
    output$downloadData <- downloadHandler(
      filename = function() {
        paste("data-", Sys.Date(), ".csv", sep="")
      },
      content = function(file) {
        Sys.sleep(5)
        write.csv(data, file)
      }
    )
  }
  
  shinyApp(ui, server)
}
```
