### ISSUE TITLE
No gray screen when app/server disconnects when using waiter

### ISSUE THREAD

**Issue by MalditoBarbudo** [JohnCoene/waiter#68]
When using waiter and an error occurs triggering the `shiny:disconnected` event, no gray screen appears. The app is not responsive anymore, but the lack of a visual hint of disconnection can be frustrating until you realize the app is not responding, especially in complex apps.

This can be reproduced clicking the `Generate error` button in the following example:

```r
library(shiny)
library(waiter)

ui <- fluidPage(
  use_waiter(),
  actionButton("draw", "draw plot"),
  actionButton("gen_error", 'Generate error'),
  plotOutput("plot")
)

server <- function(input, output){
  
  # sets: 
  # input$plot_waiter_shown
  # input$plot_waiter_hidden
  w <- Waiter$new(id = "plot")
  
  dataset <- reactive({
    input$draw
    
    w$show()
    
    on.exit({
      w$hide()
    })
    
    Sys.sleep(3)  
    
    runif(100)
  })
  
  output$plot <- renderPlot(plot(dataset()))
  
  observeEvent(
    input$gen_error,
    {
      stop('no grey, why?')
    }
  )
  
}

shinyApp(ui, server)
```

I've tracked the error to this code in `assets/waiter/custom.js` in the latest code in master:

```js
$(document).on('shiny:disconnected', function(event) {
  console.log("seems like a disconnect, hiding waiter"); // this line was added to know when this was triggered
  hide_waiter();
  Shiny.setInputValue("waiter_hidden", true, {priority: 'event'});
});
```

Following this, in the `hide_waiter` js function it seems to fail in this step:

```js
  var selector = 'body';

  if(id !== null)
    selector = '#' + id;

  var dom = document.querySelector(selector);

  var overlay = dom.getElementsByClassName("waiter-overlay");
  \\ ... the rest of the function.
```

The last line fails as the dom is already null, as shown in the chromium console:
    > waiter.js:124 Uncaught TypeError: Cannot read property 'getElementsByClassName' of null

I can think on two solutions for this:

  1. Remove the event listener in `custom.js`. If the app is disconnected anyways, there is no need of removing the waiter.

  2. Add a try-catch to the `hide_waiter` function, to catch this case and avoid the js error.

@JohnCoene If you can tell me what option you prefer (or have another one on mind), I can make a pull request with the fix ;)

**Comment by JohnCoene** [comment]
Ah! Well spotted thank you. I just removed it for now, might add it back later on :) 

Thanks again!

**Comment by MalditoBarbudo** [comment]
Nice!
Thanks for the fast fix!
