### ISSUE TITLE
remotes::install_github("JohnCoene/waiter") is requiring additinal user input.

### ISSUE THREAD

**Issue by htoor** [JohnCoene/waiter#69]
Since the CRAN version is not the latest one , Specifically only support full screen spinner, I am trying to install the package using remotes::install_github("JohnCoene/waiter") and makeit part of the docker profile. However when I run the command , I get the following prompt

Downloading GitHub repo JohnCoene/waiter@master
These packages have more recent versions available.
Which would you like to update?

 1: All                                     
 2: CRAN packages only                      
 3: None                                    
 4: R6         (2.4.0    -> 2.4.1   ) [CRAN]
 5: shiny      (1.3.2    -> 1.5.0   ) [CRAN]
 6: htmltools  (0.3.6    -> 0.5.0   ) [CRAN]
 7: rstudioapi (0.10     -> 0.11    ) [CRAN]
 8: httpuv     (1.5.2    -> 1.5.4   ) [CRAN]
 9: mime       (0.7      -> 0.9     ) [CRAN]
10: jsonlite   (1.6      -> 1.7.1   ) [CRAN]
11: digest     (0.6.20   -> 0.6.27  ) [CRAN]
12: later      (0.8.0    -> 1.1.0.1 ) [CRAN]
13: withr      (2.1.2    -> 2.3.0   ) [CRAN]
14: Rcpp       (1.0.2    -> 1.0.5   ) [CRAN]
15: BH         (1.69.0-1 -> 1.72.0-3) [CRAN]

Enter one or more numbers, or an empty line to skip updates:

How can I not get this prompt,and it simply installs it?

**Comment by ries9112** [comment]
Not really an issue relating to this package specifically so community.rstudio.com or Stackoverflow would probably be best for this kind of question (which is why I'm stepping in to answer).

You can try adding the argument `upgrade = FALSE` and see if that resolves your issue.

So try `remotes::install_github("JohnCoene/waiter", upgrade = FALSE)`
