### ISSUE TITLE
Feature: instead of having to explicitly start + hide the spinner, allow hiding the spinner automatically after an expression runs

### ISSUE THREAD

**Issue by daattali** [JohnCoene/waiter#74]
In order to minimize the work required by the developer, instead of having to do

```
waiter_show(
  html = spin_fading_circles()
) 
Sys.sleep(1)
waiter_hide() 
```

It would be much more user friendly to be able to do

```
waiter_show(
  html = spin_fading_circles(),
  expr = { Sys.sleep(1) }
) 
```

**Comment by JohnCoene** [comment]
I'm gonna go ahead and close this as I believe it's been addressed in documentation. Thanks again Dean!
