### ISSUE TITLE
Feature: Option for minified css/js

### ISSUE THREAD

**Issue by trafficonese** [JohnCoene/waiter#76]
It would be nice to have an option to get only the minified assets, similar to how [shinyjqui](https://github.com/Yang-Tang/shinyjqui/blob/948af5e507d893f5c7d22b273eb2d83fac6ea891/R/utils.R#L30) is handling it.

**Comment by JohnCoene** [comment]
All external dependencies are minified and the custom JavaScript is not that big so it should not make that much of a difference but I'll consider it.

**Comment by trafficonese** [comment]
I was mainly referring to the waiter CSS files, as those are the ones I am using often.
If you want, I can have a look at it and open a PR.

**Comment by JohnCoene** [comment]
Ah indeed, I forgot the CSS. A PR is always welcome but it would probably some convoluted setup to include the minifier so that the original CSS can still be edited.
