### ISSUE TITLE
waiter in Rmarkdown/shiny

### ISSUE THREAD

**Issue by bigomics** [JohnCoene/waiter#8]
Hi. Can waiter be used in Rmarkdown/shiny? Is there perhaps an example? Thanks. Ivo

**Comment by JohnCoene** [comment]
This is a package for shiny. There are examples in the [README](https://github.com/JohnCoene/waiter).

**Comment by bigomics** [comment]
Hi John. 

I tried the waiter example. It works in pure shiny but in rmarkdown/shiny with the code below it doesn't work. 

Ivo

```
---
runtime: shiny
---

```{r, echo=FALSE}

library(shiny)
library(waiter)

fluidPage(
    use_waiter(),
    actionButton("show", "Show loading for 3 seconds")
)

observeEvent(input$show, {
    show_waiter(spin_fading_circles())
    Sys.sleep(3) # do something that takes time
    hide_waiter()
})

```

```
