### ISSUE TITLE
Dynamic updates in waiter_show_on_load

### ISSUE THREAD

**Issue by dwachsmuth** [JohnCoene/waiter#80]
I was hoping to update the HTML in waiter_show_on_load in response to what's happening in the server as initial loading tasks are finished, but I can't get it working and can't find any documentation pointing me in the right direction. Here is what I have tried, repurposing the demo for dynamic updates from the package website:

```r
library(shiny)
library(waiter)

ui <- fluidPage(
  use_waiter(),
  waiter_show_on_load()
)

server <- function(input, output, session){

  msgs <- c("Loading data", "Running model", "Drawing plots")
  
  for(i in 1:3){
    waiter_update(html = msgs[i])
    Sys.sleep(2)
    }
  
  waiter_hide()
  
}

shinyApp(ui, server)
```

The waiter initializes correctly, and it's clear that *something* happens when it reaches the for loop in the server, because the spinner disappears, but the messages aren't displayed.

Any help would be greatly appreciated!

**Comment by JohnCoene** [comment]
This is the same as https://github.com/JohnCoene/waiter/issues/38. It was a bug on a previous version. 

I believe this has been fixed on the latest CRAN version, if that does not work the dev version on github certainly works, I just tried.

```r
# install.packages("remotes")
remotes::install_github("JohnCoene/waiter")
```

Let me know if that solves the issue

**Comment by dwachsmuth** [comment]
Arrgh, many apologies for not checking if I was on the current version of the package! Everything works fine with waiter 0.2.0. Thanks for the excellent software!

**Comment by JohnCoene** [comment]
No problem, glad it's fixed :)
