### ISSUE TITLE
Use_steward not working past v1.3

### ISSUE THREAD

**Issue by johnhubertjj** [JohnCoene/waiter#81]
Hi John, very useful R package you have here!

Just noticed that with v0.2.0 the use_steward() no longer has an animated background and instead returns all black. You can see the effect when using the reprex from your website:

```
library(shiny)
library(waiter)

ui <- fluidPage(
  use_waiter(), 
  use_steward(),
  h3("Content you will only see after loading screen has disappeared"),
  waiter_show_on_load(spin_fading_circles()) 
)

server <- function(input, output, session){
  Sys.sleep(10) # do something that takes time
  waiter_hide()
}

shinyApp(ui, server)

```

<img width="912" alt="Screenshot 2021-01-28 at 16 17 31" src="https://user-images.githubusercontent.com/21290448/106166739-669bdc80-6184-11eb-93e4-cd494c27c221.png">

**Comment by JohnCoene** [comment]
Ah, thanks for reporting this. It broke because I removed a dependency in `0.2.0`, apologies.

I just pushed a fix.
