### ISSUE TITLE
Feature Suggestion: Adding a 'alpha' variable that lets the user define transparency of the loading page

### ISSUE THREAD

**Issue by aljrico** [JohnCoene/waiter#9]
Dear @JohnCoene,

It would be awesome to have the Waiter on the whole page the way it's now but with the possibility to add some transparency to it. So the app can be seen 'underlying'. I presume that's challenging but it could open a lot of design possibilities.

I imagine it implemented as having an `alpha` parameter from 0 to 1. Similarly as it's used in many visualisations.

Thank you for your work!

**Comment by JohnCoene** [comment]
Hi Alejandro,

Thank you for the feedback, it's actually already possible, the `color` argument takes any valid css color you can achieve transparency with `rgba`.

```
# alpha = .4
color = "rgba(0, 92, 156, 0.4)"
```

Feel free to close the issue if this answers your question.

**Comment by aljrico** [comment]
Hi John,

Thank you for your answer. That absolutely solves my issue, so I'll close it.
