### ISSUE TITLE
using waiter with shiny html templates

### ISSUE THREAD

**Issue by benubah** [JohnCoene/waiter#90]
The UI definition for using a html template in Shiny is:  

`ui <- htmlTemplate(
        "www/index.html"
    )`

Any documentation on how  `waiter`  can be implemented for such a scenario?

Thank you!

**Comment by JohnCoene** [comment]
Sorry for the late response.

I have added some [documentation on the JavaScript API](https://waiter.john-coene.com/#/waiter?id=javascript), with templates you will have to use this.
