### ISSUE TITLE
Resizing window and scrolling page does not affect overlay

### ISSUE THREAD

**Issue by quirinmanz** [JohnCoene/waiter#91]
Hi,
First of all, thank you for the great package.
I use the waiter to overlay the whole page. Scrolling the page and resizing the window does not affect the overlay. It stays right where it was (the size of the window, when the waiter was shown first).
Is there a quick fix for this?
Best,
Quirin

**Comment by JohnCoene** [comment]
Apologies for the very late reply. I think this was fixed in a later version. Could you reinstall from github and let me know if you still observe this?

**Comment by JohnCoene** [comment]
I just closed, I had another look and improved that a bit more. Feel free to reopen if the issue still occurs.
