### ISSUE TITLE
Waiter doesn't start on the first actionbutton while for second actionbutton does

### ISSUE THREAD

**Issue by agronomofiorentini** [JohnCoene/waiter#93]
Hi,
First of all thank you very much for developing this package which I use for any shiny app I develop.
The user experience is greatly improved with the inclusion of these tools you have developed.

The web app reported in the following link https://agronomofiorentini.shinyapps.io/website/ is composed by golem, bs4dash, shinyalert and waiter R packages.

When I lunch the app it is all working, and waiter upload his loading progress.
Additional information is that I have placed waiter within several observeEvents, because processing often takes time.

The problem arises when I go to click the actionbutton of the observeEvent no waiter appears.
While when I try again on the same actionbutton or on another actiobutton waiter starts.
It's as if the first actionbutton doesn't activate the waiter, but the second one does and I don't understand why.

**Comment by JohnCoene** [comment]
It's difficult to look into this without code, do you have a reproducible example?

**Comment by agronomofiorentini** [comment]
I will provide to you a reproducible example as soon as possible

**Comment by agronomofiorentini** [comment]
I update the R packages and i rewrite the app with the last version of golem and now it is working perfectly.

Thanks.

**Comment by JohnCoene** [comment]
Glad to hear this!

**Comment by agronomofiorentini** [comment]
I am sorry but the issue appear again.

I will share with you a simple app that shows the problem that i described before.

`library(shiny)
library(bs4Dash)
library(waiter)

ui <- dashboardPage(
    
    title = "Waiter Issue",
    
    fullscreen = TRUE,
    
    preloader = list(html = spin_1(), color = "#333e48"),
    
    header = bs4DashNavbar(title = "Home",
                           compact = TRUE),
    
    sidebar = bs4DashSidebar(collapsed = FALSE,
                             bs4SidebarMenu(bs4SidebarMenuItem(text = "Waiter Issue",
                                                               tabName = "issue", 
                                                               icon = icon("exclamation")))),
    
    controlbar = dashboardControlbar(),
    
    footer = dashboardFooter(left = "Waiter issue",
                             right = "2021"),
    
    body = bs4DashBody(bs4TabItems(bs4TabItem(tabName = "issue",
                                              actionButton("show",
                                                           label = "First click doesn't work, while the second yes")))))


server <- function(input, output) {

    observeEvent(input$show, {
        
        waiter_show(html = spin_fading_circles())
        
        Sys.sleep(3)
        
        waiter_hide()
    })
}

shinyApp(ui = ui, server = server)`

**Comment by JohnCoene** [comment]
It's the preloader that breaks it, I have a pull request on bs4Dash that will fix that. https://github.com/RinteRface/bs4Dash/pull/213
