### ISSUE TITLE
Error downloading the latest developer version 

### ISSUE THREAD

**Issue by apalacio10** [JohnCoene/waiter#97]
Hello,

I'm trying to download the latest developer version, but I get the following error. 

`Downloading GitHub repo JohnCoene/waiter@HEAD
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  cannot open URL 'https://api.github.com/repos/JohnCoene/waiter/tarball/HEAD'`

Thanks for your help .

**Comment by JohnCoene** [comment]
Can you tell me how you are trying to install the package and the version of the package you use to install it?

**Comment by apalacio9502** [comment]
Of course, I am using the following command
`remotes::install_github("JohnCoene/waiter")`
and the remotes version is 2.4.0

**Comment by apalacio10** [comment]
Of course, I am using the following command
remotes::install_github("JohnCoene/waiter")
and the remotes version is 2.4.0

**Comment by JohnCoene** [comment]
I don't the issue is here, I have the same version of the package and it works. Can you install other packages from Github? It looks like you are behind a VPN that restricts it.

**Comment by apalacio10** [comment]
I used the same command to download other packages, for example shiny, bslib and rmarkdown. Today I download bslib again with that command and it works fine.

**Comment by JohnCoene** [comment]
Could you try again?

**Comment by apalacio10** [comment]
I just tried again and it keeps throwing the same error

**Comment by JohnCoene** [comment]
I'm sorry but I don't think it's on this end. The [link](https://api.github.com/repos/JohnCoene/waiter/tarball/HEAD) to download the tarball is valid, I've managed to install it from different networks.

**Comment by apalacio10** [comment]
Thanks,

In how many days do you plan the next release?

**Comment by JohnCoene** [comment]
@apalacio10 next month, I just pushed the last version and cannot publish any sooner (CRAN policy)

**Comment by apalacio10** [comment]
I downloaded the package and tried to install it

install.packages ("~ / Downloads / waiter-master.zip")
Warning in install.packages:
   package ‘~ / Downloads / waiter-master.zip’ is not available for this version of R

I have R version of 4.1.0

**Comment by JohnCoene** [comment]
This is really strange. I had, a week ago or so, a dependence on R 4.1.0 but no longer https://www.github.com/JohnCoene/waiter/tree/master/DESCRIPTION](https://www.github.com/JohnCoene/waiter/tree/master/DESCRIPTION)

**Comment by apalacio10** [comment]
I don't know if this is related to not being able to download the package using

`remotes::install_github("JohnCoene/waiter")`

**Comment by JohnCoene** [comment]
The error you shared with `install_github` had to do with not being able to long the GitHub endpoint (or at least that is what I understood).

You can always clone and `devtools::install()` it. If this does now work I do not know what will.
