### ISSUE TITLE
Conflict between packages DT and waiter?

### ISSUE THREAD

**Issue by dimmin** [JohnCoene/waiter#98]
Everything is said here: https://stackoverflow.com/questions/68130569/using-waiter-package-lead-to-js-error-in-shiny-with-a-dt-object

One can obtain an `Uncaught TypeError` within a DT object with waiter.

```
Uncaught TypeError: Cannot read property 'scrollIntoView' of undefined
    at HTMLDocument.document.onscroll (waiter.js:241)
    at Object.trigger (jquery.min.js:2)
    at HTMLDivElement.<anonymous> (jquery.min.js:2)
    at Function.each (jquery.min.js:2)
    at S.fn.init.each (jquery.min.js:2)
    at S.fn.init.trigger (jquery.min.js:2)
    at na (<anonymous>:74:135)
    at aa (<anonymous>:26:423)
    at v.<anonymous> (<anonymous>:140:512)
    at v.iterator (<anonymous>:113:209)
```

Here a MRE:
```r
library(shiny)
library(shinydashboard)
library(waiter)

ui <- dashboardPage(
  dashboardHeader(),
  dashboardSidebar(),
  dashboardBody(waiter::use_waiter(),
                waiter::use_steward(),
                waiter::waiter_show_on_load(),
                DT::DTOutput("rt"))
)
server <- function(input, output, session) {
  Sys.sleep(2)
  output$rt <- DT::renderDT({
    DT::datatable(mtcars,
                  selection = 'single',
                  options = list(
                    scrollX = TRUE,
                    pageLength = 8,
                    dom = 'ltp')) %>% 
      DT::formatStyle(columns = colnames(mtcars), fontSize = '90%')
  })
  waiter::waiter_hide()
}
shinyApp(ui, server)
```

**Comment by JohnCoene** [comment]
My bad, I made a mistake with the latest CRAN release. I'll fix this as soon as I can. In the meantime this is already fixed on dev.

```r
remotes::install_github("JohnCoene/waiter")
```

**Comment by dimmin** [comment]
Thanks. Any chance to have the dev version available for R 3.6.1 (currently 4.1.0)

**Comment by JohnCoene** [comment]
Done, should work now.

**Comment by dimmin** [comment]
I confirm that installing the dev version fixed this issue on both the MRE and my app. Thanks.

**Comment by dimmin** [comment]
Just for my information, why did you switch to a camelCase? (use_waiter for instance is now useWaiter)

**Comment by JohnCoene** [comment]
I find it confusing, all shiny UI code is camelCase (e.g.: `actionButton`, `selectInput`), I think waiter should follow this. 

Perhaps it's a bit too early to deprecate, I may undo this actually.

**Comment by JohnCoene** [comment]
You can reinstall the package from Github now, I've removed those .Deprecate messages.

I will deprecate those functions eventually but will spread this out over a long period, give people ample time, and find a less obnoxious way of doing so.
